name: Build FSMosquito Client

on:
  push:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - README.md
  pull_request:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - README.md

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest
    
    env:
      Solution_Name: FSMosquitoClient.sln
      Project_Path: FSMosquitoClient.csproj
      Test_Project_Path: your-test-project-path                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Execute all unit tests in the solution
    # - name: Execute unit tests
    #  run: dotnet test

    # Build FSMosquitoClient
    - name: Build the application
      run: dotnet publish $env:Project_Path --configuration Release /p:DeployOnBuild=true /p:PublishProfile="Create FSMosquitoClient Release"

    # Upload the FSMosquitoClient binaries.
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: FSMosquitoClient
        path: ${{ github.workspace }}\bin\Release\netcoreapp3.1\win10-x64\publish\**\*
